### ISSUE TITLE
USB Soundkarte

### ISSUE THREAD

**Issue by Vanixxx** [Liver64/LoxBerry-TTS#5]
Mit meiner USB-Soundkarte wird kein Ton ausgegeben.
output/usb.php:
`sox -v $volume $MessageStorepath$MP3path/$jingle -t alsa -d`
-d wählt die Standartkarte von Alsa aus?
Mit folgenden Code wird ein Ton abgespielt (in der Konsole getestet):
`sox -v $volume $MessageStorepath$MP3path/$jingle -t alsa dmix:1,0`
(Im übrigen habe ich dmix gewählt, da wenn man in Squeezelite auch dmix:1,0 verwendet, können beide Quellen gleichzeitig abgespielt werden)

**Comment by Liver64** [comment]
danke für deinen Input, habe eine Korrektur eingespielt. Bitte v1.0.1 laden und nochmal testen

**Comment by Vanixxx** [comment]
Funktioniert! Vielen Dank.
