### ISSUE TITLE
PHP-Warnings im JSON

### ISSUE THREAD

**Issue by christianTF** [Liver64/LoxBerry-TTS#7]
![73d8be67-2a05-4db3-8954-0486a018b8d3](https://user-images.githubusercontent.com/14220265/47872699-8f9b5e80-de0f-11e8-8f25-5a12be997812.jpeg)

Wenn Parameter falsch sind, kommen PHP-Warnings am Output. Der Json-Output darf nicht zerstört werden.

Ich weiß das nicht, wie das bei PHP geht:
- Vielleicht kann man die Warnings als String sammeln, und im JSON als Feld mitgeben.
- Evt. kann man die Warnings an stderr umleiten,
- oder generell deaktivieren.

**Comment by Liver64** [comment]
Ich habe einen custom error handler hinzugefügt der alle Fehler handelt, aber nichts am Screen ausgibt
