### ISSUE TITLE
MP3 Title/Artist hineinrechnen

### ISSUE THREAD

**Issue by christianTF** [Liver64/LoxBerry-TTS#8]
Per Request-Parameter soll es möglich sein, ein Processing der ID3Tags zu aktivieren:

- Der Text soll als Songtitel gesetzt werden
- Artist entweder leer, oder sowas wie "Sprachausgabe" (sprachspezifisch)

**Comment by Liver64** [comment]
ID3-Tags werden per default für jede T2S geschrieben
